security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login  

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider  
            custom_authenticator: App\Security\LoginAuthentificatorAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        # Exemple de contrôle d'accès par rôle
        # - { path: ^/admin, roles: ROLE_ADMIN }
