security:
    # Configure how passwords are hashed
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        
    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: _username  # Ensure this matches the input name
                password_parameter: _password
                success_handler: App\Security\LoginSuccessHandler

    access_control:
        - { path: ^/admin, roles: ROLE_BOUTIQUIER }
        - { path: ^/profile, roles: ROLE_VENDEUR }
        - { path: ^/login, roles: IS_ANONYMOUS }
